
let listaGatitos = `[{
    "id": 1,
    "género": "Hembra",
    "vacunas": "Todas",
    "castrado": false,
    "visita_vete": "10-22-2022",
    "tratamiento": "ninguno",
    "actividades": ["Romper cartón", "Domadora de sillón"],
    "cualidades": ["agil"],
    "discapacidad": "ninguna",
    "pelaje": "Largo",
    "carácter": ["amigable", " juguetona"],
    "enfermedades": "ninguna",
    "comida": ["iams", "pescado"],
    "img": "https://cdn.pixabay.com/photo/2015/04/23/21/59/tree-736877_960_720.jpg",
    "adoptado": false
  },
  {
    "id": 2,
    "género": "Macho",
    "vacunas": "todas",
    "castrado": true,
    "visita_vete": "si",
    "tratamiento": "ninguno",
    "actividades": ["el piso es mi mejor amigo"],
    "cualidades": ["patas marrones", "pecho blanco"],
    "discapacidad": "ninguna",
    "pelaje": "corto",
    "carácter": ["dormilón ", "miedoso" ],
    "enfermedades": "ninguna",
    "comida": ["Pedigree", "lo que haya en la mesa"],
    "img": "https://www.investigacionyciencia.es/images/21536/articleImage-minimal.jpg",
    "adoptado": false
  },
  {
    "id": 3,
    "género": "Hembra",
    "vacunas": "todas",
    "castrado": false,
    "visita_vete": "trimestral",
    "tratamiento": "gotasdiar",
    "actividades": ["juega todo el dia"],
    "cualidades": ["cariñosa"],
    "discapacidad": "visual",
    "carácter": ["sociable ", "territorial"],
    "comida": ["vitalcat"],
    "img": "https://cf.ltkcdn.net/gatos/images/std/236641-800x515r1-etapas-desarrollo-gatitos.jpg",
    "adoptado": false
  },
  {
    "id": 4,
    "género": "Macho",
    "vacunas": "todas",
    "castrado": false,
    "visita_vete": "10-22-2022",
    "tratamiento": "ninguno",
    "actividades": ["dormilon"],
    "cualidades": ["es bueno con los niños"],
    "discapacidad": "largo",
    "pelaje": "false",
    "carácter": ["mimoso ", "curioso"],
    "enfermedades": "ninguna",
    "comida": ["excellent"],
    "img": "https://cdn.pixabay.com/photo/2016/02/19/15/46/labrador-retriever-1210559_960_720.jpg",
    "adoptado": false
  },
  {
    "id": 5,
    "género": "Hembra",
    "vacunas": "Todas",
    "castrado": true,
    "visita_vete": "10-22-2022",
    "tratamiento": "ninguno",
    "actividades": ["Correr", "Jugar"],
    "cualidades": ["mimoso"],
    "discapacidad": "ninguna",
    "pelaje": "Corto",
    "carácter": ["temperamental", " traviesa"],
    "enfermedades": "ninguna",
    "comida": ["Nutrique"],
    "img": "https://cdn.pixabay.com/photo/2016/11/29/11/26/dog-1869167_960_720.jpg",
    "adoptado": false
  },
  {
    "id": 6,
    "género": "Hembra",
    "vacunas": "Todas",
    "castrado": false,
    "visita_vete": "10-22-2022",
    "tratamiento": "ninguno",
    "actividades": ["Perseguir su cola", "Ladrarle a los pájaros"],
    "cualidades": ["Juguetona, cariñosa"],
    "discapacidad": "Ninguna",
    "carácter": ["tímida ", "tranquila"],
    "enfermedades": "Ninguna",
    "comida": ["Carne cruda"],
    "img": "https://i.picsum.photos/id/237/3500/2095.jpg?hmac=y2n_cflHFKpQwLOL1SSCtVDqL8NmOnBzEW7LYKZ-z_o",
    "adoptado": false
  },
  {
    "id": 7,
    "género": "Hembra",
    "vacunas": "todas",
    "castrado": false,
    "visita_vete": "03-08-2022",
    "tratamiento": "no",
    "actividades": ["Comer", "salir a pasear", "dormir"],
    "cualidades": ["corre rápido", "salta en dos patas"],
    "discapacidad": "no",
    "carácter": ["dulce", " compañera" ],
    "enfermedades": "ninguna",
    "comida": ["Comida balanceada", "carne", "arroz", "verduras"],
    "img": "https://www.tiendanimal.es/articulos/wp-content/uploads/2020/03/galgo.jpg",
    "adoptado": false
  },
  {
    "id": 8,
    "género": "Macho",
    "vacunas": "2",
    "castrado": false,
    "visita_vete": "03-06-2022",
    "tratamiento": "no",
    "actividades": ["cazador", "sociable"],
    "cualidades": ["trepador"],
    "discapacidad": "ninguna",
    "pelaje": "Corto",
    "carácter": ["inquieto "],
    "enfermedades": "no",
    "comida": ["purina", "pollo"],
    "img": "https://cdn.pixabay.com/photo/2016/06/14/00/14/cat-1455468_960_720.jpg",
    "adoptado": false
  },
  {
    "id": 9,
    "género": "Hembra",
    "vacunas": "No se sabe",
    "castrado": false,
    "visita_vete": "-",
    "tratamiento": "ninguno",
    "actividades": ["Duerme", "Juega con pompóm", "Rasguña muebles"],
    "cualidades": ["Trepadora"],
    "discapacidad": "Ninguna",
    "pelaje": "Largo",
    "carácter": ["amistosa", " juguetona"],
    "enfermedades": "Ninguna",
    "comida": ["leche", "pollo"],
    "img": "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2021-12/EL%20PRIMER%20D%C3%8DA%20DE%20UN%20GATO%20NUEVO%20EN%20CASA-1.jpg?itok=peJkgf-V",
    "adoptado": false
  },
  {
    "id": 10,
    "género": "Macho",
    "vacunas": true,
    "castrado": false,
    "visita_vete": "5-12-2022",
    "tratamiento": "ninguno",
    "actividades": ["Buscar rastros", "correr"],
    "cualidades": ["buen olfato", "inteligente"],
    "discapacidad": "ninguna",
    "pelaje": "corto",
    "carácter": ["miedoso", " curioso"],
    "enfermedades": "ninguna",
    "comida": ["perrarina", "carne"],
    "img": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F47%2F2021%2F08%2F23%2Fpictures-of-german-shepherds-2000.jpg",
    "adoptado": true
  },
  {
    "id": 11,
    "género": "Macho",
    "vacunas": "Completas",
    "castrado": true,
    "visita_vete": "15-10-2022",
    "tratamiento": "Ninguno",
    "actividades": ["Pasear con su peluche", "dormir", "jugar"],
    "cualidades": ["dócil ", "divertido"],
    "discapacidad": "ninguna",
    "pelaje": "Corto",
    "carácter": ["cariñoso"],
    "enfermedades": "ninguna",
    "comida": ["Royal canin"],
    "img": "https://www.animalfiel.com/wp-content/uploads/2020/07/perro-mediano-shiba-inu.jpg",
    "adoptado": false
  },
  {
    "id": 12,
    "género": "Hembra",
    "vacunas": "Completas",
    "castrado": true,
    "visita_vete": "Al dia",
    "tratamiento": "Ninguno",
    "actividades": ["Dormir , comer ,jugar"],
    "cualidades": ["Cariñosa"],
    "discapacidad": "Ninguna",
    "pelaje": "Corto",
    "carácter": ["mimosa ", "inquieta"],
    "enfermedades": "Ninguna",
    "comida": ["Royal canin"],
    "img": "https://www.notigatos.es/wp-content/uploads/2016/03/gato_mestizo.jpg.webp",
    "adoptado": true
  },
  {
    "id": 13,
    "género": "Hembra",
    "vacunas": "Todas",
    "castrado": false,
    "visita_vete": "10-22-2022",
    "tratamiento": "ninguno",
    "actividades": ["Abrir tacho de basura", "Cazar bichitos"],
    "cualidades": ["agil"],
    "discapacidad": "ninguna",
    "pelaje": "Largo",
    "carácter": ["solitaria ", "tranquila"],
    "enfermedades": "ninguna",
    "comida": ["excellent", "pollo"],
    "img": "https://www.dogalize.com/wp-content/uploads/2017/02/image1.jpg",
    "adoptado": true
  },
  {
    "id": 14,
    "género": "Macho",
    "vacunas": "completas",
    "castrado": false,
    "visita_vete": "10-05-2022",
    "tratamiento": "ninguno",
    "actividades": [
      "pasear",
      "jugar con juguetes para gatitos",
      "dormir mucho"
    ],
    "cualidades": ["saltarina"],
    "discapacidad": "ninguna",
    "pelaje": "Largo y blanco",
    "carácter": ["cariñoso"],
    "enfermedades": "ninguna",
    "comida": ["Pedigree", "comida casera"],
    "img": "https://www.webconsultas.com/sites/default/files/styles/wch_image_schema/public/temas/gato_persa.jpg",
    "adoptado": false
  },
  {
    "id": 15,
    "género": "Macho",
    "vacunas": "Ninguna",
    "castrado": false,
    "visita_vete": "Ninguna",
    "tratamiento": "Ninguno",
    "actividades": [
      "Cazar ratones, subirse a los techos y controlar el bienestar de los vecinos"
    ],
    "cualidades": ["Te mantiene el barrio libre de ratones"],
    "discapacidad": "Ninguna",
    "pelaje": "Largo",
    "carácter": ["divertido ", "curioso"],
    "enfermedades": "Ninguna",
    "comida": ["Ratones"],
    "img": "https://cdn.pixabay.com/photo/2020/02/26/19/33/cats-4882615_960_720.jpg",
    "adoptado": false
  },
  {
    "id": 16,
    "género": "Macho",
    "vacunas": "Todas",
    "castrado": true,
    "visita_vete": "04-14-2022",
    "tratamiento": "ninguno",
    "actividades": ["Dormir", "Afilar garras en todo tipo de telas"],
    "cualidades": ["dormilona"],
    "discapacidad": "ninguna",
    "pelaje": "Corto",
    "carácter": ["sociable ", "compañero" ],
    "enfermedades": "ninguna",
    "comida": ["iams", "pescado"],
    "img": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F47%2F2020%2F08%2F07%2Fgray-tabby-american-shorthair_757090435-1-2000.jpg",
    "adoptado": false
 

}]`

var misGatitos = JSON.parse(listaGatitos);

export default misGatitos